PROMPT *******************************
PROMPT Script start: grants.sql
PROMPT *******************************

DEFINE SCHEMA_NAME = &&1

PROMPT Granting privileges to &&SCHEMA_NAME

GRANT CREATE PROCEDURE TO &SCHEMA_NAME;
GRANT CREATE SEQUENCE TO &SCHEMA_NAME;
GRANT CREATE TABLE TO &SCHEMA_NAME;
GRANT CREATE TYPE TO &SCHEMA_NAME;
GRANT CREATE TRIGGER TO &SCHEMA_NAME;
GRANT CREATE SYNONYM TO &SCHEMA_NAME;
GRANT CREATE SESSION TO &SCHEMA_NAME;
GRANT CREATE ANY DIRECTORY TO &SCHEMA_NAME;
GRANT CREATE TABLE TO &&SCHEMA_NAME;

UNDEFINE SCHEMA_NAME

PROMPT *******************************
PROMPT Script start: grants.sql
PROMPT *******************************