CREATE TABLE WORKER 
(
  ID NUMBER NOT NULL 
, KOD NUMBER 
, LAST_NAME VARCHAR2(50) 
, FIRST_NAME VARCHAR2(50) 
, POSITION VARCHAR2(50) 
, DEPARTMENT_ID NUMBER 
, CONSTRAINT WORKER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE DEPARTMENT 
(
  ID NUMBER NOT NULL 
, NUMBER_DEP NUMBER 
, DEPARTMENT_NAME VARCHAR2(50)
, CONSTRAINT DEPARTMENT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);