CREATE TABLE PERSON 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 100 MINVALUE 100 NOT NULL 
, FIRST_NAME VARCHAR2(50) 
, LAST_NAME VARCHAR2(50) 
, SECOND_NAME VARCHAR2(50) 
, EMAIL VARCHAR2(100) 
, CONSTRAINT PK_PERSON PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PERSON_PK ON PERSON (ID ASC) 
  )
  ENABLE 
) 
TABLESPACE MMF_120_0_DATA;

COMMENT ON COLUMN PERSON.ID IS 'Уникальный идентификатор таблицы PERSON';
COMMENT ON COLUMN PERSON.FIRST_NAME IS 'Имя';
COMMENT ON COLUMN PERSON.LAST_NAME IS 'Фамилия';
COMMENT ON COLUMN PERSON.SECOND_NAME IS 'Отчество';
COMMENT ON COLUMN PERSON.EMAIL IS 'Элеткронная почта';
