INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Иванов','Тимофей','timohatimafeikq@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Крайний','Эдвард','ekrayniy@inbox.ru');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Данилевич','Матвей','danilevichmathew@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Петрушина','Ева','piatrushinae@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Гаврук','Александр','sanganious@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Иванов','Владислав','vladislavivanov440@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Воробьёва','Дарья','dyuvorobeva@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Грищенко','Дарья','dasha.gr.gom@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Белявская','Елизавета','mmf.belyavsk@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Кривицкая','Полина','polinakrivitskaya14@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Склименок','Евгения','eugene.sklimenok@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Буйко','Алина','alinamobil2016@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Мисюкевич','Дарья','missukevitch@gmail.com ');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Сидорова','Алина','alinasidorova2812@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Зарудко','Игнат','ascendp6n9@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Пархоменко','Георгий','george.parhomenko@yandex.ru');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Поздняков','Иван','aivanpozdnyakov@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Черкасов','Роман','chero858@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Бабурин','Владислав','vlad.babur.vb@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Болбат','Дмитрий','bolbadim@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Рабащенко','Владислав','vlad.rabashchenko@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Торч','Илья','itorch2001@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Плешко','Дмитрий','pleshko.dima19@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Стаганович','Алексей','stagantank@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Смоленский','Захар','z.smolensz@gmail.com ');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Стукач','Дмитрий','stukachdima06112000@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Смирнов','Игорь','smirnou.igor@gmail.com ');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Бондарчик','Альбина','bondarchikalya@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Жаврид','Мария','nomoresorrow23@gmail.com');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Колодич','Антон','mmf.kolodichAS@bsu.by');
INSERT INTO PERSON FIRST_NAME, LAST_NAME, EMAIL VALUES('Суражев','Кирилл','surazhevkirillleonidovich@gmail.com');